using System;
using Jampiler.Core;

namespace Jampiler.AST
{
    /// <summary>
    /// Represents a node in the abstract syntax tree structure generated by the parser.
    /// Each node contains a type, a value and has the possibility to store other nodes to the left and right.
    /// </summary>
    public class Node
    {
        public TokenType Type { get; set; }

        public string Value { get; set; }

        public Node Left { get; set; }

        public Node Right { get; set; }

        public Node(TokenType type, string value)
        {
            Type = type;
            Value = value;
        }

        public Node(TokenType type, string value, Node left, Node right) : this(type, value)
        {
            Left = left;
            Right = right;
        }

        public Node(Token token) : this(token.Type, token.Value) { }

        public Node(Token token, Node left, Node right) : this(token)
        {
            Left = left;
            Right = right;
        }

        public override string ToString()
        {
            return string.Format("{{ {0} }} {{ {1} }}", Type, Value);
        }

        /// <summary>
        /// Recursive function used to print out this node and all of its children.
        /// Useful for debugging the structure of the abstract syntax tree.
        /// </summary>
        public void Print(string indent = "", string prefix = "N")
        {
            Logger.Instance.Debug(string.Format("{0}{1} {2}", indent, prefix, ToString()));

            indent += "  ";
            var copy = indent.Clone().ToString();

            Left?.Print(indent, "L");
            Right?.Print(copy, "R");
        }
    }
}
